export enum DocumentAttributeVideoTokensEnum {
  DOCUMENT_ATTRIBUTE_VIDEO_SERVICE_TOKEN = 'DOCUMENT_ATTRIBUTE_VIDEO_SERVICE_TOKEN',
  DOCUMENT_ATTRIBUTE_VIDEO_REPOSITORY_TOKEN = 'DOCUMENT_ATTRIBUTE_VIDEO_REPOSITORY_TOKEN',
}
